# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Bayesian Methods in Asset Pricing
author: Thomas Martins
logo: BAP_logo.png
copyright: "2024"

# Force re-execution of notebooks on each build.
# See 
execute:
  execute_notebooks: force
  timeout: -1

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: BAP_book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year
bibtex_bibfiles: 
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/thomasmartins/BAP_book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: This book is available under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license.